spring:
datasource:
url: pi3.cqvqyg6mm892.us-east-1.rds.amazonaws.com
username: Grupo10
password: Grupo10Legal
driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
hibernate:
ddl-auto: update  # Para dev; use 'validate' em prod
show-sql: true