spring.application.name=chatOn
# Banco H2 do JVM
spring.datasource.url=jdbc:h2:~/test;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.h2.console.enabled=true
spring.h2.console.path=/console
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

# Banco no MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/globalchat
#spring.datasource.username=root
#spring.datasource.password=P@$$W0RD
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.profiles.active=prod

# Banco de dados PostgresSQL (Supabase - AWS S3)
#spring.datasource.url=jdbc:postgresql://db.{ida da aplicação}.supabase.co:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=pi3sADPPRW@#
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect